Feature branch
rehanullah748/setup-mobile-skeleton pull request #1
Opened 2022-08-16 21:05 UTC by rehanullah748

2022-08-17 19:52 UTC, Abenezer-Tilahun requested changes
Hi @rehanullah748  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

✔️ No linter errors.
✔️ You used correct Github Flow.

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [ ] README file should be descriptive and  all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) should be present in your Repo. 
- [ ] Please try to use meaningful Commit messages in your feature project.(at this moment you are not required to update the commit messages)
- [ ] Pull Request should have a descriptive title telling you what changes are inside and should have a summary describing introduced changes in more detail.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 19:52 UTC, Abenezer-Tilahun commented on index.html
> +        </header>
- [ ] Good job for using `header` tag for toolbar section , `a` for log and `nav` tag for hamburger menu. But for hamburger menu you try to import `menu.png` form images folder unfortunately there is no images folder in your Repo, so please try to fix it
![review](https://user-images.githubusercontent.com/93598189/185222152-5032f6b4-259d-4a0d-aaa8-894f422a4d6f.PNG)
.

2022-08-17 19:52 UTC, Abenezer-Tilahun commented on index.html
> +        </div>
- [ ] For background image you try to import images from images folder but unfortunately there is no images folder in your Repo, so please try to fix it.

2022-08-17 19:52 UTC, Abenezer-Tilahun commented on index.html
> +        </main>
- [ ] Please try to use `section` tag for container of headline section.

2022-08-17 19:52 UTC, Abenezer-Tilahun commented on index.html
> +            </div>
- [ ] for the list of Social icons please try to uses a `ul` tag to group them, and `li` per icon; each icon  must has a link `a` tag.
- [ ] for `a` tag please try to  connect your social networks with the icons, using `href`.

2022-08-17 19:52 UTC, Abenezer-Tilahun commented on index.html
> +        <div class="ellipse-bottom-right"><img src="images/Ellipse12.png" alt=""></div>
- [ ] For background image you try to import images from images folder but unfortunately there is no images folder in your Repo, so please try to fix it.

2022-08-17 19:52 UTC, Abenezer-Tilahun commented on index.html
> +
- Please try to  align the elements according to the requirement, you should use Flexbox in all 2 sections(toolbar and headline section.)

- Both toolbar and headline section must have the margins (top, bottom, left, right) defined in the Template design.
-    You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

Your project looks like this
![Backgr](https://user-images.githubusercontent.com/93598189/185227809-6791d511-dfd2-4dc3-abb8-899fa7d39825.PNG)

The Figma design looks like :

![Figma design](https://user-images.githubusercontent.com/93598189/185227877-12c9398c-c2e2-4a87-82ed-bb34053f2750.PNG)

2022-08-17 19:52 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] Good job for implementing styling pages but please try to stick to the design as much as possible (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

2022-08-17 19:52 UTC, Abenezer-Tilahun commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] Good job for proffesional README.
- [ optional] README file should be descriptive and all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) should be present in a your repo and please try to customize.

2022-08-18 21:23 UTC, mwanawabangona approved these changes
Hi @rehanullah748,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job getting approved on your first try!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 13:49 UTC, merged